---
title: "STAT628 HW2"
author: "Zhihao ZHAO"
date: "2020/10/17"
output: word_document
---
```{r}
setwd("C:/Users/THINKPAD/Desktop/myUW/STAT628 Data Science Practicum/HW2")

BodyFat=read.table("BodyFat.csv", header=T,sep=",")
attach(BodyFat)
```

```{r}
summary(BodyFat)
sd(BODYFAT)
```




####visualization
```{r}
par(mfrow=c(2,2)) #Makes a two-by-two, i.e. (2,2), plotting window
par(mgp=c(1.8,.5,0), mar=c(3,3,1,1)) #"Beautifies" plots when creating multiple figures. Google this for more info.

hist(BODYFAT,breaks=30,cex.lab=1.5,cex.main=1.5,
     main="Histogram of Body Fat %",xlab="Body Fat %")
hist(AGE,breaks=30,cex.lab=1.5,cex.main=1.5,
     main="Histogram of Age",xlab="Age (yrs)")
hist(WEIGHT,breaks=30,cex.lab=1.5,cex.main=1.5,
     main="Histogram of Weight",xlab="Weight (lbs)")
hist(HEIGHT,breaks=30,cex.lab=1.5,cex.main=1.5,
     main="Histogram of Height",xlab="Height (inch)")

```


```{r}
par(mfrow=c(2,2)) #Makes a two-by-two, i.e. (2,2), plotting window
par(mgp=c(1.8,.5,0), mar=c(3,3,1,1)) #"Beautifies" plots when creating multiple figures. Google this for more info.

hist(ADIPOSITY,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(NECK,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(CHEST,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(ABDOMEN,breaks=30,cex.lab=1.5,cex.main=1.5,)

```

```{r}
par(mfrow=c(2,2)) #Makes a two-by-two, i.e. (2,2), plotting window
par(mgp=c(1.8,.5,0), mar=c(3,3,1,1)) #"Beautifies" plots when creating multiple figures. Google this for more info.

hist(HIP,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(THIGH,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(KNEE,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(ANKLE,breaks=30,cex.lab=1.5,cex.main=1.5,)
```

```{r}
par(mfrow=c(2,2)) #Makes a two-by-two, i.e. (2,2), plotting window
par(mgp=c(1.8,.5,0), mar=c(3,3,1,1)) #"Beautifies" plots when creating multiple figures. Google this for more info.

hist(BICEPS,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(FOREARM,breaks=30,cex.lab=1.5,cex.main=1.5,)
hist(WRIST,breaks=30,cex.lab=1.5,cex.main=1.5,)
```

```{r}
BodyFat[WEIGHT > 350,]#totally outlier: many index is the max outlier
```


#########Calculate BodyFat outlier
```{r}
495/DENSITY-450#not the same with in .csv
```

```{r}
TEMP=1/DENSITY
lm(BODYFAT~1+TEMP)
```

```{r}
448.2/DENSITY-405.8
```

```{r}
BodyFat[BODYFAT<5,]
lowFat=BodyFat[BODYFAT<5,]
Fat=448.2/lowFat[,3]-405.8
Fat####   outlier #182
```

#####Height outlier
```{r}
lowHgt=BodyFat[HEIGHT<30,]
trueHgt=sqrt((0.4536*lowHgt[5])/lowHgt[7])/0.0254
trueHgt####69.43
```

#####Ankle outlier
```{r}
BodyFat[ANKLE>30,]
```


######data cleaning
```{r}
BodyFat[42,6]=69.43
BodyFat=BodyFat[-c(39,172,182),]
BodyFat=BodyFat[,-c(1,3)]
```


############Model Construction
```{r}
library(car)
model.all=lm(BODYFAT~.,data=BodyFat)
summary(model.all)
#Anova(model.all)
```
```{r}
vif(model.all)
```

```{r}
model.sig<-lm(BODYFAT~1+AGE+ABDOMEN+WRIST,data=BodyFat)
summary(model.sig)### R^2=0.729, good enogh since model.all = 0.750
#Anova(model.sig)
```



```{r}
model.step<-step(model.sig,scope=list(upper=model.all,lower=model.sig),
                 direction="forward")
summary(model.step)
```

```{r}
predict.lm(model.sig,newdata=data.frame(AGE=40,ABDOMEN=90,WRIST=18,HEIGHT=70,CHEST=100,FOREARM=29,NECK=38),interval = "prediction", level= 0.95,se.fit=T)
```

```{r}
anova(model.sig,model.all)
```

```{r}
confint(model.sig)
```

```{r}
par(mfrow = c(1,3))
plot(predict(model.sig),resid(model.sig,data=BodyFat),pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
    xlab="Predicted Body Fat %", ylab="Standardized Residuals",main="Standardized Residual Plot")
abline(a=0,b=0,col="black",lwd=3)
qqnorm(rstandard(model.sig),pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
      main="Normal QQ Plot of the Residuals")
abline(a=0,b=1,col="black",lwd=3)
plot(BodyFat$BODYFAT,predict.lm(model.sig),pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
    xlab="Predicted Body Fat %", ylab="Observed ",main="Fitness test")
abline(0,1,col="black",lwd=3)

```

```{r}
pii = hatvalues(model.sig)
cooki = cooks.distance(model.sig)

par(mfrow = c(2,1))
n = dim(BodyFat)[1]
plot(1:n,pii,type="p",pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
     xlab="Index (Each Observation)",ylab="Pii",main="Leverage Values (Pii)")
plot(1:n,cooki,type="p",pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
     xlab="Index (Each Observation)",ylab="Cook's Distance",main="Influence Values (Cook's Distance)")

```

























